# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    default_config: my_config
    configs:
        my_config:
            language: '%locale%'
            toolbar: full
            htmlEncodeOutput: false
            allowedContent: true
            removePlugins: 'exportpdf'
            format_tags: 'p;h2;h3;h4;h5;pre'
            contentsCss: ['/assets/bootstrap/bootstrap.min.css', '/assets/ckeditor-contents.css']
    toolbars:
        configs: 
            basic: ['@basic.basic_styles', '@basic.paragraph', '@basic.links']
            full: [ 
                '@full.document', 
                '@full.clipboard',
                '@full.editing', 
                '@full.links',
                '@full.insert',
                '@full.colors',
                '@full.tools',
                '/',
                '@full.basic_styles',
                '@full.paragraph',
                '@full.styles',
            ]
        items:
            basic.basic_styles: ["Bold", "Italic",  'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']
            basic.paragraph: [
                'NumberedList',
                'BulletedList',
                '-',
                'Outdent',
                'Indent',
                '-',
                'Blockquote',
                '-',
                'JustifyLeft',
                'JustifyCenter',
                'JustifyRight',
                'JustifyBlock',
            ]
            full.styles: ['Styles', 'Format', 'Font', 'FontSize']
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
