# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: "lazy"

    filter_sets:
        icon_image:
            filters:
                thumbnail:
                    size: [35, 25]
                    mode: outbound

        gallery_thumbnail:
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound
        
        card_image:
            filters:
                thumbnail:
                    size: [305, 280]
                    mode: outbound
                    allow_upscale: false

        medium_image:
            filters:
                thumbnail:
                    size: [700, 1000]
                    mode: inset
                    allow_upscale: false

