sonata_admin:
    security:
        handler: sonata.admin.security.handler.role

    title: 'Administration'
    templates:
        layout: Admin/extend_layout.html.twig
    dashboard:
        blocks:
             -
                position: top
                class: col-md-12
                type: sonata.block.service.text
                settings: 
                    content: >
                        <h1 class="dashboard-title">Tableau de bord</h1>
                        <div class"row">
                        <p class="description col-md-9" style="padding-left:0">Bienvenue sur le panneau d'administration. Ici, vous allez pouvoir gérer l'encyclopédie et son contenu.</p>
                        <div class="col-md-3 text-right" style="padding-right:0">
                            <a href="/admin/app/image/download" class="btn btn-sm btn-primary"><i class="fas fa-download"></i> Télécharger les images</a>
                        </div>
                        </div>
             - { type: sonata.admin.block.admin_list, position: left }
             -
                position: right
                type:     sonata.admin.block.admin_preview
                settings:
                    code:  admin.article
                    icon:  fas fa-magic
                    limit: 7
                    text:  Latest Edited Articles
                    filters:
                        _sort_by:    createdAt
                        _sort_order: DESC
             -
                position: right
                type:     sonata.admin.block.stats
                settings:
                    code:  admin.article
                    icon:  fas fa-magic
                    text:  published articles
                    color: bg-blue

    assets:
        extra_stylesheets: [ assets/admin.css ]
            

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
    http_cache: false
