twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        app_version: '%env(APP_VERSION)%'
        app_name: '%env(WIKI_NAME)%'
        app_description: '%env(WIKI_DESCRIPTION)%'
        enable_contact: '%env(bool:ENABLE_CONTACT)%'
        enable_registration: '%env(bool:ENABLE_REGISTRATION)%'
        background_color: '%env(BACKGROUND_COLOR)%'
        date_format: '%env(DATE_FORMAT)%'
        enable_comment: '%env(COMMENT_MODULE)%'
        enable_idiom: '%env(IDIOM_MODULE)%'
        enable_forum: '%env(FORUM_MODULE)%'
        enable_scenario: '%env(SCENARIO_MODULE)%'
        enable_private_message: '%env(PM_MODULE)%'

when@test:
    twig:
        strict_variables: true
