twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        app_name: '%env(WIKI_NAME)%'
        app_description: '%env(WIKI_DESCRIPTION)%'
        enable_contact: '%env(bool:ENABLE_CONTACT)%'
        enable_registration: '%env(bool:ENABLE_REGISTRATION)%'
        background_color: '%env(BACKGROUND_COLOR)%'
        date_format: '%env(DATE_FORMAT)%'

when@test:
    twig:
        strict_variables: true
