controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"