controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"