# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.enable.registration: '%env(bool:ENABLE_REGISTRATION)%' 
    app.enable.contact: '%env(bool:ENABLE_CONTACT)%' 
    app.website.name: '%env(WIKI_NAME)%'
    app.contact.mail: '%env(CONTACT_EMAIL)%' 
    app.contact.name: '%env(CONTACT_NAME)%'
    app.backup.folder: '%kernel.project_dir%/backup'
    app.tmp.folder: '%kernel.project_dir%/var/cache'
    app.per_page_odd: '%env(PER_PAGE_ODD_COLUMNS)%'
    app.per_page_even: '%env(PER_PAGE_EVEN_COLUMNS)%'
    locale: fr

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $enableRegistration: '%app.enable.registration%'
            $enableContact: '%app.enable.contact%'
            $websiteName: '%app.website.name%'
            $contactMail: '%app.contact.mail%'
            $contactName: '%app.contact.name%'
            $backupFolder: '%app.backup.folder%'
            $perPageOdd: '%app.per_page_odd%'
            $perPageEven: '%app.per_page_even%'
            $configFile: '%kernel.project_dir%/.env.local'
            $publicDir: '%kernel.project_dir%/public'
            $projectDir: '%kernel.project_dir%/'
            $enableComment: '%env(COMMENT_MODULE)%'
            $enableIdiom: '%env(IDIOM_MODULE)%'
            $enableForum: '%env(FORUM_MODULE)%'
            $enableScenario: '%env(SCENARIO_MODULE)%'
            $enablePrivateMessage: '%env(PM_MODULE)%'
            $tmpDir: '%app.tmp.folder%'
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Twig\SettingsExtension:
        arguments:
            $faviconFile: '%env(WIKI_FAVICON)%'
            $bannerFile: '%env(WIKI_BANNER)%'

    App\Service\Modules\ModuleService:
        arguments: 
            $modules: [
                { 
                    id: 'IDIOM_MODULE',
                    title: 'Langues',
                    icon: 'fas fa-language',
                    description: "Ce module permet de gérer sur l'encyclopédie des langues qui comprennent des articles que vous pouvez regrouper par catégorie."
                },
                {
                    id: 'SCENARIO_MODULE',
                    title: 'Scénarios',
                    icon: 'fas fa-book',
                    description: "Ce module intègre à l'application un système de conception de scénario dans lequel vous pouvez réordonner les épisodes."
                },
                { 
                    id: 'COMMENT_MODULE',
                    title: 'Commentaires',
                    icon: 'fas fa-comment-alt',
                    description: "Ce module permet aux utilisateurs connectés de poster des commentaires sur les articles de l'encyclopédie."
                },
                {
                    id: 'FORUM_MODULE',
                    title: 'Forum',
                    icon: 'fas fa-comments',
                    description: "Ce module permet d'intégrer au site un forum de discussion pour échanger avec vos membres et les personnes qui contribuent."
                },
                {
                    id: 'PM_MODULE',
                    title: 'Messagerie privée',
                    icon: 'fas fa-inbox',
                    description: "Ce module intègre à l'application un système de messagerie privée entre les membres inscrits à l'application."
                }
                
            ]
